//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Osb.Core.Platform.Business.Util.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BusinessExcMsg
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public BusinessExcMsg()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Osb.Core.Platform.Business.Util.Resources.BusinessExcMsg", typeof(BusinessExcMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ExternalIdentifier obrigatório.
        /// </summary>
        public static string EXC0001
        {
            get
            {
                return ResourceManager.GetString("EXC0001", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login obrigatório.
        /// </summary>
        public static string EXC0002
        {
            get
            {
                return ResourceManager.GetString("EXC0002", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OperationType é obrigatório.
        /// </summary>
        public static string EXC0003
        {
            get
            {
                return ResourceManager.GetString("EXC0003", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AccountId é obrigatório.
        /// </summary>
        public static string EXC0004
        {
            get
            {
                return ResourceManager.GetString("EXC0004", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TaxId é obrigatório.
        /// </summary>
        public static string EXC0005
        {
            get
            {
                return ResourceManager.GetString("EXC0005", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to StartDate é obrigatório.
        /// </summary>
        public static string EXC0006
        {
            get
            {
                return ResourceManager.GetString("EXC0006", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EndDate é obrigatório.
        /// </summary>
        public static string EXC0007
        {
            get
            {
                return ResourceManager.GetString("EXC0007", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Não é possível realizar uma Transferência Interna com data inferior a atual.
        /// </summary>
        public static string EXC0008
        {
            get
            {
                return ResourceManager.GetString("EXC0008", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Conta remetente não encontrada.
        /// </summary>
        public static string EXC0009
        {
            get
            {
                return ResourceManager.GetString("EXC0009", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Conta destinatária não encontrada.
        /// </summary>
        public static string EXC0010
        {
            get
            {
                return ResourceManager.GetString("EXC0010", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Número do documento é obrigatório.
        /// </summary>
        public static string EXC0011
        {
            get
            {
                return ResourceManager.GetString("EXC0011", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status da transação inválido.
        /// </summary>
        public static string EXC0012
        {
            get
            {
                return ResourceManager.GetString("EXC0012", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dados bancários da conta destinatária não encontrado.
        /// </summary>
        public static string EXC0013
        {
            get
            {
                return ResourceManager.GetString("EXC0013", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ActualDateTransfer inválido.
        /// </summary>
        public static string EXC0014
        {
            get
            {
                return ResourceManager.GetString("EXC0014", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BankCode é obrigatório.
        /// </summary>
        public static string EXC0015
        {
            get
            {
                return ResourceManager.GetString("EXC0015", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AccountType é obrigatório.
        /// </summary>
        public static string EXC0016
        {
            get
            {
                return ResourceManager.GetString("EXC0016", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CellPhone é obrigatório.
        /// </summary>
        public static string EXC0017
        {
            get
            {
                return ResourceManager.GetString("EXC0017", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UserTaxId é obrigatório.
        /// </summary>
        public static string EXC0018
        {
            get
            {
                return ResourceManager.GetString("EXC0018", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CompanyId é obrigatório.
        /// </summary>
        public static string EXC0019
        {
            get
            {
                return ResourceManager.GetString("EXC0019", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to DocumentNumber é obrigatório.
        /// </summary>
        public static string EXC0020
        {
            get
            {
                return ResourceManager.GetString("EXC0020", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email é obrigatório.
        /// </summary>
        public static string EXC0021
        {
            get
            {
                return ResourceManager.GetString("EXC0021", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AccountTaxId é obrigatório.
        /// </summary>
        public static string EXC0022
        {
            get
            {
                return ResourceManager.GetString("EXC0022", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AccountName é obrigatório.
        /// </summary>
        public static string EXC0023
        {
            get
            {
                return ResourceManager.GetString("EXC0023", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name é obrigatório.
        /// </summary>
        public static string EXC0024
        {
            get
            {
                return ResourceManager.GetString("EXC0024", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BankAccountDigit é obrigatório.
        /// </summary>
        public static string EXC0025
        {
            get
            {
                return ResourceManager.GetString("EXC0025", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BankAccount é obrigatório.
        /// </summary>
        public static string EXC0026
        {
            get
            {
                return ResourceManager.GetString("EXC0026", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type é obrigatório.
        /// </summary>
        public static string EXC0027
        {
            get
            {
                return ResourceManager.GetString("EXC0027", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BankBranch é obrigatório.
        /// </summary>
        public static string EXC0028
        {
            get
            {
                return ResourceManager.GetString("EXC0028", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bank é obrigatório.
        /// </summary>
        public static string EXC0029
        {
            get
            {
                return ResourceManager.GetString("EXC0029", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status é obrigatório.
        /// </summary>
        public static string EXC0030
        {
            get
            {
                return ResourceManager.GetString("EXC0030", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status inválido.
        /// </summary>
        public static string EXC0031
        {
            get
            {
                return ResourceManager.GetString("EXC0031", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MoneyTransferId obrigatório.
        /// </summary>
        public static string EXC0032
        {
            get
            {
                return ResourceManager.GetString("EXC0032", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to InternalTransferId obrigatório.
        /// </summary>
        public static string EXC0033
        {
            get
            {
                return ResourceManager.GetString("EXC0033", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Número do usuario é obrigatório.
        /// </summary>
        public static string EXC0034
        {
            get
            {
                return ResourceManager.GetString("EXC0034", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Campo de data obrigatório.
        /// </summary>
        public static string EXC0035
        {
            get
            {
                return ResourceManager.GetString("EXC0035", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UserId é obrigatório.
        /// </summary>
        public static string EXC0036
        {
            get
            {
                return ResourceManager.GetString("EXC0036", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VerificationCode é obrigatório.
        /// </summary>
        public static string EXC0037
        {
            get
            {
                return ResourceManager.GetString("EXC0037", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PhoneNumber é obrigatório.
        /// </summary>
        public static string EXC0038
        {
            get
            {
                return ResourceManager.GetString("EXC0038", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VerificationCode ou PhoneNumber é necessário.
        /// </summary>
        public static string EXC0039
        {
            get
            {
                return ResourceManager.GetString("EXC0039", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TaxId inválido.
        /// </summary>
        public static string EXC0040
        {
            get
            {
                return ResourceManager.GetString("EXC0040", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Favorecido já foi cadastrado anteriormente.
        /// </summary>
        public static string EXC0041
        {
            get
            {
                return ResourceManager.GetString("EXC0041", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Número do identificador não informado.
        /// </summary>
        public static string EXC0042
        {
            get
            {
                return ResourceManager.GetString("EXC0042", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TagAmount é obrigatório.
        /// </summary>
        public static string EXC0043
        {
            get
            {
                return ResourceManager.GetString("EXC0043", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Usuário de acesso não corresponde ao informado na requisição.
        /// </summary>
        public static string EXC0044
        {
            get
            {
                return ResourceManager.GetString("EXC0044", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UserId é obrigatório.
        /// </summary>
        public static string EXC0045
        {
            get
            {
                return ResourceManager.GetString("EXC0045", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Usuário de acesso não tem autorização a conta informada.
        /// </summary>
        public static string EXC0046
        {
            get
            {
                return ResourceManager.GetString("EXC0046", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BarCode é obrigatório.
        /// </summary>
        public static string EXC0047
        {
            get
            {
                return ResourceManager.GetString("EXC0047", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ActualDatePayment é obrigatório.
        /// </summary>
        public static string EXC0048
        {
            get
            {
                return ResourceManager.GetString("EXC0048", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Transferência não pode mais ser cancelada
        /// </summary>
        public static string EXC0049
        {
            get
            {
                return ResourceManager.GetString("EXC0049", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Transferência não encontrada
        /// </summary>
        public static string EXC0050
        {
            get
            {
                return ResourceManager.GetString("EXC0050", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CardIdentifier inválido.
        /// </summary>
        public static string EXC0051
        {
            get
            {
                return ResourceManager.GetString("EXC0051", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Esse cartão já está aguardando ativação.
        /// </summary>
        public static string EXC0052
        {
            get
            {
                return ResourceManager.GetString("EXC0052", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Número do identificador do cartão não informado.
        /// </summary>
        public static string EXC0053
        {
            get
            {
                return ResourceManager.GetString("EXC0053", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Número do pin não informado.
        /// </summary>
        public static string EXC0054
        {
            get
            {
                return ResourceManager.GetString("EXC0054", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Código de motivo para a inavatição do cartão não informada.
        /// </summary>
        public static string EXC0055
        {
            get
            {
                return ResourceManager.GetString("EXC0055", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pin informado é inválido.
        /// </summary>
        public static string EXC0056
        {
            get
            {
                return ResourceManager.GetString("EXC0056", resourceCulture);
            }
        }
    }
}